### ISSUE TITLE
something went wrong. contact support

### ISSUE THREAD

**Issue by PythonCoderAS** [vivekweb2013/gitnoter#38]
I am trying to use the site, and I used the auto repository creator. I go to make a very simple note, and I get "something went wrong. contact support."

Note title: HelloWorld
Note Content:
> How are you! This is **cool**.

![Image](https://user-images.githubusercontent.com/13932583/163657558-2f7c8367-3267-430e-9e01-fbba63b65700.png)

**Comment by vivekweb2013** [comment]
Please check if there is already a note with `HelloWorld` in the root path

**Comment by PythonCoderAS** [comment]
> Please check if there is already a note with `HelloWorld` in the root path

There is nothing. It's a brand new repository. It has no files.

**Comment by vivekweb2013** [comment]
Strange. Could you please try the below things.
- Log off. clear cache. log in & try again. If it fails again try the below step
- Click on the `profile > settings > change notes repository` then select any other repo and save

Let me know if it still presents the same error.

**Comment by Dairy-Farming** [comment]
Getting the same issue. Something went wrong. Contact support. Tried another repository. Tried using different names for Note Title. Tried on different browsers. No luck

**Comment by vivekweb2013** [comment]
> Getting the same issue. Something went wrong. Contact support. Tried another repository. Tried using different names for Note Title. Tried on different browsers. No luck

I've checked the backed for and it seems that there is some issue with your repository. The below error is logged
```
time="2022-04-16T06:01:28Z" level=error msg="request failed due to internal server error" error_message="retrieving branch ref failed: GET https://api.github.com/repos/Dairy-Farming/notes/git/ref/heads/main: 404 Not Found []"
```

Are you sure you have the `notes` repository with branch `main` inside it. It could happen that after setting up the repo you have deleted it from your account.

**Comment by PythonCoderAS** [comment]
> > Getting the same issue. Something went wrong. Contact support. Tried another repository. Tried using different names for Note Title. Tried on different browsers. No luck
> 
> I've checked the backed for and it seems that there is some issue with your repository. The below error is logged
> 
> ```
> time="2022-04-16T06:01:28Z" level=error msg="request failed due to internal server error" error_message="retrieving branch ref failed: GET https://api.github.com/repos/Dairy-Farming/notes/git/ref/heads/main: 404 Not Found []"
> ```
> 
> Are you sure you have the `notes` repository with branch `main` inside it. It could happen that after setting up the repo you have deleted it from your account.

Oh here is where the error starts. I defined my account to use master as the default branch.

**Comment by spartan4cs** [comment]
![image](https://user-images.githubusercontent.com/23625985/164032227-9213578d-2ccb-422d-8ee0-eed1971cf0fe.png)

**Comment by PythonCoderAS** [comment]
> there is option to set default branch due to which notes private repo is getting created with master branch

I am aware this is an option. I am saying that it would be better if gitnoter could automatically find the default branch, or at least mention that a main branch has to exist.

**Comment by vivekweb2013** [comment]
> > there is option to set default branch due to which notes private repo is getting created with master branch
> 
> I am aware this is an option. I am saying that it would be better if gitnoter could automatically find the default branch, or at least mention that a main branch has to exist.

yeah right. I'm working on the fix

**Comment by schnitzelaufzug** [comment]
Same issue, with default branch main. Any suggestions?

**Comment by vivekweb2013** [comment]
@schnitzelaufzug @PythonCoderAS @Dairy-Farming

I've just fixed the issue. Could you please try deleting the `notes` repo. Login to gitnoter and use setup repo automatically option.

GitNoter will now fetch the default branch of the repository and use it instead of defaulting to `main` branch.

**Comment by schnitzelaufzug** [comment]
Same issue

**Comment by vivekweb2013** [comment]
> Same issue

Could you please let me know if you have deleted the notes repo before automatic setup. Also please check and let me know the branch name of the notes repo. Is it the master branch?

**Comment by schnitzelaufzug** [comment]
The branch name is main and i deleted the old one and automatically created a new one again.

**Comment by vivekweb2013** [comment]
> The branch name is main and i deleted the old one and automatically created a new one again.

Then I think it should not cause any error. What error are you getting? Could you please try in incognito mode. I'm not able to reproduce this issue.

**Comment by schnitzelaufzug** [comment]
Same error in incognito.
Error message: "something went wrong. contact support"

**Comment by schnitzelaufzug** [comment]
Can u see the logs?

**Comment by vivekweb2013** [comment]
> Can u see the logs?

Strange. I'm getting below error
```
PUT https://api.github.com/repos/schnitzelaufzug/notes/contents/README.md: 422 Validation Failed [{Resource:committer Field:name Code:missing_field Message:}]
```

I'm investigating the issue

**Comment by vivekweb2013** [comment]
> Allright, let me know when i can test agian.

Fixed. Please try now

**Comment by schnitzelaufzug** [comment]
awsome, works!

**Comment by PythonCoderAS** [comment]
Works for me!
