### ISSUE TITLE
On settings view, show email if the user's name field is empty

### ISSUE THREAD

**Issue by vivekweb2013** [vivekweb2013/gitnoter#40]
The settings component shows the user details including user's name, location etc but the user's name field can be empty for some user's

In such case we should show the email which is always available.

Refer below file for the changes
[https://github.com/vivekweb2013/gitnoter/blob/main/frontend/src/components/Settings.tsx](https://github.com/vivekweb2013/gitnoter/blob/main/frontend/src/components/Settings.tsx)

**Comment by ritikBhandari** [comment]
Him
Can I take up this issue?

**Comment by vivekweb2013** [comment]
> Hi, Can I take up this issue?

Sure

**Comment by vivekweb2013** [comment]
Done
