### ISSUE TITLE
Design a 404 page not found view inside react frontend

### ISSUE THREAD

**Issue by vivekweb2013** [vivekweb2013/gitnoter#45]
If the user visits a link for which there is no route defined, then we should show a 404 page not found view.

As a part of this task

- Create a new 404 component
- Add a 404 route at the end of all routes which matches all the paths. This route should render the 404 view.

**Comment by shikhar13012001** [comment]
I would like to work on this issue. @vivekweb2013

**Comment by vivekweb2013** [comment]
> I would like to work on this issue. @vivekweb2013

Sure @shikhar13012001 
Let me know if you face any issue

**Comment by vivekweb2013** [comment]
@shikhar13012001 Please refer this readme for instruction on how to run the frontend app locally
https://github.com/vivekweb2013/gitnoter/blob/main/frontend/README.md

**Comment by shikhar13012001** [comment]
Hi @vivekweb2013 I have made the 404 page
![image](https://user-images.githubusercontent.com/75368010/169636019-e4683dc3-14e9-4367-a2e8-6308aba37437.png)
I have made the PR for the same, please review and let me know if you require any changes

**Comment by vivekweb2013** [comment]
wow this is awesome 🤩 . Thanks so much. It looks great!
I'd just like to suggest just one minor change. Please amend the commit message from "Added 404 page" to "Add 404 page". IMO a good commit message should use the imperative, present tense. It is easier to read and scan quickly :)

**Comment by shikhar13012001** [comment]
@vivekweb2013  yeah sure I make the commit message change

**Comment by vivekweb2013** [comment]
@shikhar13012001 thanks let me know once you push the changes. I'll merge this pr and we can then test it on production.

**Comment by vivekweb2013** [comment]
@shikhar13012001 I think I messed up something with the force push to your repository :( and I'm not able to revert it.
if you have **issue#45** branch checked out locally please force push it.

**Comment by vivekweb2013** [comment]
@shikhar13012001 fixed it. I've cherry picked the commit and amended the commit message. Pushed the changes to production. Please check [https://gitnoter.com](https://gitnoter.com)

Thanks so much for the contribution :)
